name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - josemejias11

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🚁

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce this issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: ios-version
    attributes:
      label: iOS Version
      description: What version of iOS are you running?
      options:
        - iOS 17.x
        - iOS 16.x  
        - iOS 15.x
        - iOS 14.x
        - iOS 13.x
    validations:
      required: true

  - type: dropdown
    id: drone-model
    attributes:
      label: Drone Model
      description: Which DJI drone are you using?
      options:
        - DJI Mini 4 Pro
        - DJI Mini 3 Pro
        - DJI Mini 3
        - DJI Mini 2
        - DJI Air 3
        - DJI Air 2S
        - DJI Mavic 3
        - DJI Mavic Air 2
        - Other (please specify in description)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Safety Confirmation
      description: By submitting this issue, you confirm that you are following all safety guidelines
      options:
        - label: I am following all local drone regulations
          required: true
        - label: I am operating the drone in a safe environment  
          required: true
        - label: I have tested this in a controlled environment
          required: true
